---
title: "Select_Phenotypes"
author: "Jennifer Blanc"
date: "2023-01-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list =ls())
```

# Load all phenotypes
```{r}
# Read in all phenotypes 
phenos <- fread("~/Downloads/phenotypes.both_sexes.tsv")

#t <- phenos %>% filter(phenotype == "20002")

# Select only binary variables
phenos <- phenos %>% filter(variable_type == "binary")

# Select only phenotypes with non-missing data > 10,000
phenos <- phenos %>% filter(n_non_missing > 10000)
```

# Load heritability results
```{r}
h2 <- fread("~/Downloads/ukb31063_h2_topline.02Oct2019.tsv.gz")

# Pick binary phenotypes
h2 <- h2 %>% filter(isBinary == TRUE)

# Pick h2 > 0.01
h2 <- h2 %>% filter(h2_liability > 0.01 )

# Remove phenotypes with notes
h2 <- h2 %>% filter(notes == "" )

# Pick high or medium confidence h2
h2 <- h2 %>% filter(confidence %in% c("high", "medium"))

# Pick significant h2 
h2 <- h2 %>% filter(h2_sig %in% c("z4", "z7"))
```

# Load field mappings
```{r}
fm <- fread("~/Downloads/UKBB_fieldMappings.csv")

# Subset to Disease
fm <- fm %>% filter(type %in% c("Disease", "DIsease"))
```

# Load Significant SNP number 
```{r}
snp <- fread("../output/results/snp_number_0.01.txt")
```

## Get list
```{r}
colnames(snp)[1] <- "phenotype"
df <- inner_join(phenos, snp)

## Stringent p-val threshold at least 10 SNPs
dfS <- df %>% filter(`p-1e-08` >= 10)

## Leinient p-val threshold at least 100 SNPs
dfL <- df  %>% filter(`p-1e-05` >= 10)


for (i in 1:nrow(dfS)) {
  filename <- paste0(dfS$phenotype[i], ".gwas.imputed_v3.both_sexes.tsv.bgz")
  cmd <- paste0("touch ../output/file_names/Stringent/", filename)
  system(cmd)
}

for (i in 1:nrow(dfL)) {
  filename <- paste0(dfL$phenotype[i], ".gwas.imputed_v3.both_sexes.tsv.bgz")
  cmd <- paste0("touch ../output/file_names/Lenient/", filename)
  system(cmd)
}
```






